### ISSUE TITLE
兄弟文档写的有点问题

### ISSUE THREAD

**Issue by HeliumzzZ** [sujoshua/newCQUPTCheckin#4]
secret应该是JZDXXDZ不是ADDRESS

**Comment by sujoshua** [comment]
现在在添加那个push功能，代码更新了，文档现在还在写，抱歉了

**Comment by HeliumzzZ** [comment]
没事没事 大佬牛的 我自己fork了改了 这部分 已经能用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月7日(星期三) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sujoshua/newCQUPTCheckin] 兄弟文档写的有点问题 (Issue #4)





 
现在在添加那个push功能，代码更新了，文档现在还在写，抱歉了
